name: eductionapp
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - asset/man.png
    - asset/bulb.png
    - asset/C-1.png
    - asset/C-2.png
    - asset/C-3.png
    - asset/C-4.png
